spring.application.name=events
server.port=8082

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/events_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:134257}
spring.datasource.driver-class-name=org.postgresql.Driver